name: Conda Matrix Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            pip
            pytest
            flake8
            rich
            nbformat
            ipykernel
            nbconvert
          cache-environment: true
          cache-downloads: true

      - name: Confirm environment
        run: |
          which python
          python --version
          which pip
          pip list
          pip install smartrun 

      - name: Install requirements.txt if present
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests and examples
        run: |
          PYTHONPATH=. pytest
          PYTHONPATH=. python examples/t1.py 
          PYTHONPATH=. python examples/t2.py
          PYTHONPATH=. python examples/t3.py